"""

예외 처리 구문 

try:
    print("try 블록 실행")  # 여기서 예외가 발생할 가능성이 있음
except Exception as e:
    print(f"예외 발생: {e}")
else:
    print("else 블록 실행")  # 예외가 발생하지 않으면 실행

"""

# try:
#     print("예외가 발생할 수 있는 구문입니다.")
#     # raise 이 주석을 해제하면, 예외가 발생했습니다가 출력이 된다.
# except Exception as e:
#     print("예외가 발생했습니다.")
# else:
#     print("예외가 발생하지 않았습니다.")
# finally:
#     print("예외 처리 구문이 끝났습니다.")

"""
2. 
"""

